import type { Context, Config } from '@netlify/functions'
import { getStore } from '@netlify/blobs'

// Página pública e interactiva para completar la "ficha completa" de una propiedad
// desde un enlace, en /llenar/<id>. Quien recibe el enlace puede rellenar todos los
// campos, agregar o eliminar filas (arrendatarios y propietarios anteriores) sin
// límite, adjuntar archivos, guardar (se almacena en Netlify Blobs y vuelve a la app
// con "Traer cambios"), y exportar/compartir en PDF, Word, Excel, WhatsApp, correo o SMS.

const SECS: Array<{ t: string; ico: string; f: Array<[string, string, string?]> }> = [
    {t:"Datos básicos de la operación",ico:"",f:[["tipoOperacion","Tipo de operación (venta / arriendo / arriendo c/ opción / leasing)"],["alias","Nombre o alias interno"],["tipoPropiedad","Tipo de propiedad"],["condInmueble","Condición (nuevo / como nuevo / usado)"],["uso","¿Para qué se usa?"],["direccion","Dirección (calle)"],["unidad","N° / Depto - Oficina - Local"],["pisoUbica","Piso en que está"],["villaCondominio","Villa / Condominio / Edificio"],["sectorBarrio","Sector / Barrio de referencia"],["comuna","Comuna"],["ciudad","Ciudad"],["region","Región"],["codigoPostal","Código postal"],["coordenadas","Coordenadas / link Google Maps"]]},
    {t:"Identificación legal y catastral",ico:"",f:[["rolSII","Rol S.I.I."],["fojas","Inscripción CBR — Fojas"],["numeroInsc","Inscripción CBR — N°"],["anoInsc","Inscripción CBR — Año"],["cbr","Conservador de Bienes Raíces"],["propInscrito","Nombre del propietario inscrito"],["propInscritoRut","RUT del propietario inscrito"],["tipoPropietario","Tipo de propietario (persona / sociedad / cooperativa / sucesión)"],["repLegalSoc","Representante legal (si es persona jurídica)"],["repLegalRut","RUT del representante legal"],["anoConstruccion","Año de construcción (aprox.)"],["recepcionFinal","Recepción final de obras municipal"],["regularizacion","Regularización vigente (DFL 2 / Ley / sin / N/A)"],["hipotecaGravamen","Hipoteca o gravamen vigente"],["hipotecaBancoMonto","Si tiene hipoteca: banco y monto aprox."],["prohibiciones","Prohibiciones vigentes"],["servidumbres","Servidumbres"],["litigios","Litigios o juicios"],["reglamentoCopro","Reglamento de copropiedad — Fojas/N°/Año"],["notariaEscritura","Notaría y fecha de la escritura"],["codigoVerif","Código de verificación de la escritura"],["form2890","Formulario 2890 SII — N° / fecha"],["noExpropMuni","Certificado no expropiación municipal — fecha"],["noExpropServiu","Certificado no expropiación SERVIU — fecha"],["certNumero","Certificado de número (DOM) — fecha"],["permisoEdif","Permiso de edificación — N° / fecha"]]},
    {t:"Superficies",ico:"",f:[["superfTerreno","Superficie de terreno (m²)"],["superfConstruida","Superficie construida total (m²)"],["superfUtil","Superficie útil / vendible (m²)"],["superfTerraza","Superficie terraza o balcón (m²)"],["superfJardin","Superficie jardín privado (m²)"],["superfEstacCubierto","Superficie estacionamiento cubierto (m²)"],["superfBodega","Superficie bodega(s) (m²)"],["superfLocal","Superficie local comercial (m²)"],["fuenteSuperficies","Fuente de superficies (plano / escritura / tasación / medición)"]]},
    {t:"Programa habitacional y distribución",ico:"",f:[["dormitorios","N° de dormitorios"],["banos","N° de baños completos (ducha/tina)"],["banosWC","N° de baños de agua (WC + lavamanos)"],["banoServicio","N° de baños de servicio"],["dependenciaServicio","Dependencia de servicio (sí indep. / compartida / no)"],["estacionamientos","N° de estacionamientos cubiertos"],["estacDescubiertos","N° de estacionamientos descubiertos"],["bodegas","N° de bodegas"],["pisosTotalesCasa","Pisos totales de la casa"],["totalPisosEdificio","N° total de pisos del edificio"],["orientacion","Orientación principal"],["tipoCirculacion","Circulación (ascensor / escalera / acceso directo)"]]},
    {t:"Características y terminaciones",ico:"",f:[["tipoCocina","Tipo de cocina (americana / independiente / semi)"],["equipCocina","Equipamiento de cocina incluido"],["mueblesCocina","Tipo de muebles de cocina"],["areaLavanderia","Área de lavandería"],["conexLavadora","Conexiones lavadora/secadora"],["calefaccion","Calefacción"],["aguaCaliente","Agua caliente"],["aireAcond","Aire acondicionado / ventilación"],["conexGas","Conexión de gas"],["pisosPrincipales","Pisos principales (material)"],["ventanas","Ventanas (aluminio / termopanel / madera / PVC)"],["protecciones","Protecciones (rejas / alarma / cortinas)"],["extrasEquip","Otro equipamiento (alarma, cámara, domótica, paneles, piscina, quincho)"],["terminacionesEspeciales","Terminaciones especiales / remodelaciones / elementos de valor"]]},
    {t:"Estado general y ocupación actual",ico:"",f:[["estadoConserv","Estado general del inmueble"],["ocupacionActual","Ocupación actual"],["dispVisitasDesde","Disponible para visitas desde","date"],["dispEntregaDesde","Disponible para entrega desde","date"],["restriccionVisitas","Restricciones de horario para visitas"],["llavesContacto","Quién tiene las llaves / contacto para acceso"],["visitaSinAviso","¿Se permite visitar sin aviso previo?"]]},
    {t:"Situación de arriendo",ico:"",f:[["arrendadaActual","¿Arrendada actualmente?"],["desocupadaDesde","Si NO: desocupada desde","date"],["motivoDesocupada","Si NO: motivo"],["arriendoUF","Arriendo mensual (UF)"],["arriendoCLP","Arriendo equivalente (CLP)"],["reajuste","Reajuste"],["diaPago","Día de pago"],["multa","Multa por atraso (%)"],["formaPago","Forma de pago"],["bancoCuenta","Banco y N° de cuenta"],["gastoComunQuienPaga","Gasto común: monto y quién paga"],["serviciosANombre","Servicios a nombre de"]]},
    {t:"Arrendatario actual",ico:"",f:[["aNombre","Nombre completo"],["aRut","RUT"],["aNacionalidad","Nacionalidad"],["aProfesion","Profesión u ocupación"],["aEmpleador","Empleador o actividad"],["aEmail","Correo"],["aTelefono","Teléfono"],["aWhatsapp","WhatsApp"],["aOcupantes","N° de ocupantes"],["avalNombre","Aval / codeudor — Nombre"],["avalRut","Aval — RUT"],["avalContacto","Aval — contacto"],["estadoPagos","Estado de pagos (al día / atrasos / cobranza)"],["tipoContratoVigente","Tipo de contrato (Residencial Ley 18.101 / Comercial / Verbal)"],["clausulaTermino","Cláusula de término anticipado pactada"],["garantiaMonto","Garantía (CLP)"],["garantiaMeses","Garantía — meses"],["garantiaFecha","Garantía — fecha recibida","date"],["garantiaEstado","Estado de la garantía"],["tipoContrato","Tipo de contrato (formato)"],["contratoInicio","Inicio del contrato","date"],["contratoTermino","Término del contrato","date"],["notariaContrato","Notaría / protocolizado"],["comisionCorretaje","Comisión de corretaje"]]},
    {t:"Antecedentes (InfoCheck)",ico:"",f:[["icPuntaje","Puntaje InfoCheck"],["icCapacidad","Capacidad de pago (CLP)"],["icRenta","Renta líquida (CLP)"],["icDeudaCMF","Deuda directa CMF (CLP)"],["icFuente","Fuente de ingresos"],["icFecha","Fecha del informe","date"]]},
    {t:"Información urbanística y normativa",ico:"",f:[["planRegulador","Plan Regulador aplicable"],["zonaSubzona","Zona o subzona (ZM1, R2, ZU-4…)"],["coefConstruct","Coeficiente de constructibilidad"],["coefOcupSuelo","Coeficiente de ocupación de suelo"],["alturaMax","Altura máxima permitida (m / pisos)"],["usosSuelo","Usos de suelo permitidos"],["cip","CIP (Certificado de Informaciones Previas)"],["afectacionesUP","Afectaciones de utilidad pública"],["detalleAfectaciones","Detalle de afectaciones"],["declaratoriaPatrimonial","Declaratoria patrimonial / conservación histórica"],["detalleDeclaratoria","Detalle declaratoria"]]},
    {t:"Crédito hipotecario",ico:"",f:[["tieneCredito","¿Tiene crédito vigente?"],["banco","Banco o institución"],["tipoCredito","Tipo de crédito"],["nOperacion","N° de operación"],["dividendoUF","Dividendo mensual (UF)"],["dividendoCLP","Dividendo equivalente (CLP)"],["dividendosTotales","N° total de dividendos"],["dividendosPagados","Dividendos pagados"],["creditoInicio","Inicio del crédito","date"],["creditoTermino","Término estimado","date"],["tasaInteres","Tasa de interés (%)"],["segurosDividendo","Seguros incluidos en dividendo"],["ejecutivoBanco","Ejecutivo / contacto"],["alzamiento","Alzamiento de hipoteca (fecha)"]]},
    {t:"Aspectos financieros (venta / arriendo)",ico:"",f:[["precioPublicadoEn","Precio publicado en (UF / CLP / USD)"],["precioVentaUF","Precio de venta solicitado (UF / CLP)"],["precioArriendoUF","Precio de arriendo mensual (UF / CLP)"],["esNegociable","El precio es (negociable / fijo / a tratar)"],["precioMinInterno","Precio mínimo aceptable (uso interno)"],["tasacionCLP","Tasación comercial (CLP)"],["tasacionUF","Tasación comercial (UF)"],["fechaTasacion","Fecha de la tasación","date"],["tasador","Tasador o banco"],["arriendoMercadoUF","Arriendo de mercado (UF)"],["aceptaHipotecario","Acepta financiamiento hipotecario"],["aceptaLeasing","Acepta leasing habitacional"],["condicionesPago","Condiciones especiales de pago"]]},
    {t:"Gastos, cargas y seguros",ico:"",f:[["contribucionesAno","Contribuciones SII al año (CLP)"],["contribAlDia","Contribuciones al día — fecha"],["avaluoFiscal","Avalúo fiscal SII (CLP)"],["afectaContrib","¿Afecta o exenta de contribuciones?"],["gastoComun","Gastos comunes mensuales (CLP)"],["gcIncluye","Gastos comunes incluyen (agua/gas/electricidad/seguro…)"],["deudaGC","Deuda de gastos comunes"],["seguroIncendioUF","Seguro incendio+sismo (UF/año)"],["otrosSeguros","Otros seguros"],["vigenciaSeguros","Vigencia de seguros"],["mantenciones","Mantenciones periódicas"]]},
    {t:"Áreas comunes y amenidades (edificio / condominio)",ico:"",f:[["amenidades","Amenidades (piscina, gimnasio, quincho, portería 24h, cámaras, etc.)"],["nPisosEdificio","N° de pisos del edificio"],["nUnidadesEdificio","N° de unidades del edificio / condominio"],["nTorres","N° de torres"],["administracionEdificio","Administración del edificio"],["adminContacto","Nombre y contacto del administrador"]]},
    {t:"Propiedad comercial / industrial",ico:"",f:[["usoActualComercial","Uso actual del inmueble"],["usosAnteriores","Usos anteriores relevantes"],["patenteComercial","Patente comercial vigente"],["frenteCalle","Frente a la calle (m lineales)"],["alturaLibre","Altura libre interior (m)"],["accesoCarga","Acceso de carga / descarga"],["potenciaElectrica","Potencia eléctrica instalada (kW) / trifásico"],["instalEspeciales","Instalaciones especiales (extracción, cámara frigorífica…)"],["estacClientes","N° estacionamientos para clientes"],["derechoLlave","Derecho de llave (valor)"],["nombreNegocio","Nombre del negocio actual (venta en marcha)"]]},
    {t:"Servicios básicos",ico:"",f:[["elecEmpresa","Electricidad — empresa y N° cliente"],["aguaEmpresa","Agua — empresa y N° cliente"],["gasEmpresa","Gas — empresa y N° cliente"],["internetEmpresa","Internet/TV — empresa y N° cliente"],["medidores","N° de medidores (luz / agua / gas)"],["otrosServicios","Otros suministros"]]},
    {t:"Documentación disponible",ico:"",f:[["documentosDisponibles","Documentos listos para entregar (escritura, dominio vigente, hipotecas y gravámenes, litigios, avalúo, rol, CIP, tasación, planos, permiso, recepción, reglamento, recibos, contrato, fotos, tour 360°…)"]]},
    {t:"Descripción para publicar y aspectos destacados",ico:"",f:[["descripcionAviso","Descripción principal (para el aviso — máx. 800 caracteres)"],["aspectosPositivos","Aspectos positivos a destacar"],["advertencias","Aspectos a aclarar / advertencias"],["palabrasClave","Palabras clave o etiquetas"],["autorizaDireccion","¿Autoriza publicar dirección exacta? (sí / solo comuna / bajo consulta)"],["autorizaFotosExt","¿Autoriza publicar fotos exteriores?"],["autorizaFotosInt","¿Autoriza publicar fotos interiores?"],["portales","Portales en los que se desea publicar"]]},
    {t:"Datos del propietario / mandante",ico:"",f:[["propNombre","Nombre completo"],["propRut","RUT"],["propTelPrincipal","Teléfono principal"],["propTelAlt","Teléfono alternativo"],["propEmail","Email"],["propDireccionPostal","Dirección postal (para notificaciones)"],["propApoderado","Representante / apoderado"],["propApoderadoRut","RUT del representante"],["medioContacto","Medio de contacto preferido"],["horarioContacto","Horario de contacto preferido"],["corredora","Corredora o corredor asignado"],["corredorTel","Teléfono corredor/a"],["corredorEmail","Email corredor/a"],["exclusividad","Exclusividad de la corredora (con / sin)"],["comisionAcordada","Comisión acordada"]]},
    {t:"Otros contactos clave",ico:"",f:[["repLegal","Representante legal de la sociedad"],["adminEdificio","Administración / conserjería"],["abogado","Abogado"],["contador","Contador"]]},
    {t:"Instrucciones internas y notas (uso interno)",ico:"",f:[["precioMinimoPiso","Precio mínimo aceptable (piso de negociación, UF)"],["urgencia","Urgencia de venta / arriendo (alta / media / baja)"],["otrosInteresados","¿Hay otros interesados conocidos?"],["motivoVenta","Motivo de la venta / arriendo (confidencial)"],["condicionesLimitaciones","Condiciones especiales o limitaciones del propietario"],["historialRelevante","Historial relevante del inmueble"],["fechaRecepcionFicha","Fecha de recepción de la ficha","date"],["ingresadoPor","Ingresado por"],["codigoInterno","Código interno del inmueble"]]}
]
const notFound = () =>
  new Response(
    '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Ficha no disponible</title><style>body{font-family:system-ui,Segoe UI,sans-serif;background:#0f1115;color:#e7e9ee;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0;text-align:center;padding:24px}.b{max-width:440px}h1{font-size:22px;margin:0 0 10px}p{color:#9aa3b2;line-height:1.6}</style></head><body><div class="b"><h1>Este enlace no está disponible</h1><p>Puede haber expirado o ya no existe. Pide a quien te lo envió que comparta el enlace nuevamente.</p></div></body></html>',
    { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
  )

export default async (req: Request, context: Context) => {
  const id = String((context.params as Record<string, string>)?.id || '').replace(/[^a-z0-9]/gi, '').slice(0, 24)
  if (!id) return notFound()
  const store = getStore('fichas-completas')
  const data: any = await store.get(id, { type: 'json' })
  if (!data) return notFound()
  return new Response(buildPage(id, data), { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
}

function buildPage(id: string, data: any) {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Completar ficha de propiedad</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;background:#eef1f6;color:#16202f;line-height:1.5;padding:0 0 60px}
.top{background:#1F3A5C;color:#fff;padding:18px 20px;position:sticky;top:0;z-index:5}
.top h1{font-size:18px}.top p{opacity:.85;font-size:13px;margin-top:3px}
.wrap{max-width:920px;margin:16px auto;padding:0 14px}
.sec{background:#fff;border-radius:12px;box-shadow:0 4px 18px rgba(0,0,0,.06);padding:14px 16px;margin-bottom:14px}
.sec h2{font-size:15px;color:#1F3A5C;margin-bottom:10px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}
.fld label{display:block;font-size:12px;font-weight:600;color:#5a6678;margin-bottom:3px}
input,textarea{width:100%;border:1px solid #d3dae6;border-radius:8px;padding:9px 10px;font-size:15px;font-family:inherit;background:#fff}
input:focus,textarea:focus{outline:none;border-color:#1F3A5C;box-shadow:0 0 0 3px rgba(43,95,166,.12)}
textarea{min-height:80px;resize:vertical}
table.rows{width:100%;border-collapse:collapse}
table.rows th{text-align:left;font-size:11px;color:#5a6678;padding:3px 4px}
table.rows td{padding:2px 3px}table.rows input{padding:7px 8px;font-size:13px}
.x{background:#fff0f0;border:1px solid #f4cccc;color:#c0392b;border-radius:7px;padding:6px 9px;cursor:pointer;display:inline-flex;align-items:center;justify-content:center}
.add{display:inline-block;margin-top:8px;background:#eef3fb;border:1px solid #cfe0f5;color:#1F3A5C;border-radius:8px;padding:8px 12px;font-weight:700;cursor:pointer;font-size:14px}
.file{display:flex;align-items:center;gap:8px;border:1px solid #e1e6ef;border-radius:8px;padding:6px 10px;margin-bottom:6px;font-size:13px}.file a{color:#1F3A5C;text-decoration:none;flex:1}
.bar{position:sticky;bottom:0;background:#fff;border-top:1px solid #e1e6ef;box-shadow:0 -4px 18px rgba(0,0,0,.06);padding:12px 14px;display:flex;flex-wrap:wrap;gap:8px;justify-content:center;z-index:5}
.b{border:1px solid #cfd6e2;background:#fff;border-radius:9px;padding:11px 16px;font-weight:700;font-size:14px;cursor:pointer;font-family:inherit}
.b.green{background:#1f9d57;border-color:#1f9d57;color:#fff}.b.blue{background:#1F3A5C;border-color:#1F3A5C;color:#fff}
.msg{text-align:center;font-weight:700;color:#1f9d57;margin-top:10px;min-height:20px}
</style></head><body>
<div class="top"><h1 id="ttl">Completar ficha de propiedad</h1><p>Rellena la información, guarda y, si quieres, expórtala o compártela. Los campos vacíos se pueden dejar en blanco.</p></div>
<div class="wrap">
  <div id="form"></div>
  <div class="sec"><h2>Arrendatarios anteriores</h2><div id="ant"></div><button class="add" onclick="addAnt()">+ Agregar arrendatario anterior</button></div>
  <div class="sec"><h2>Propietarios anteriores (cadena de dominio)</h2><div id="due"></div><button class="add" onclick="addDue()">+ Agregar propietario anterior</button></div>
  <div class="sec"><h2>Observaciones</h2><textarea id="f_observaciones" placeholder="Comentarios, pendientes, particularidades…"></textarea></div>
  <div class="sec"><h2>Documentos adjuntos</h2><div id="arch"></div><label class="add">Adjuntar archivos<input type="file" multiple style="display:none" onchange="onFiles(this)"></label></div>
  <div class="msg" id="msg"></div>
</div>
<div class="bar">
  <button class="b green" onclick="save()">Guardar</button>
  <button class="b" onclick="expPDF()">PDF</button>
  <button class="b" onclick="expWord()">Word</button>
  <button class="b" onclick="expExcel()">Excel</button>
  <button class="b" onclick="shWA()">WhatsApp</button>
  <button class="b" onclick="shMail()">Correo</button>
  <button class="b" onclick="shSMS()">SMS</button>
</div>
<script>
var FID=${JSON.stringify(id)};
var SECS=${JSON.stringify(SECS)};
var DATA=${JSON.stringify(data)};
var ANT=Array.isArray(DATA.arrendatariosAnteriores)?DATA.arrendatariosAnteriores.slice():[];
var DUE=Array.isArray(DATA.duenosAnteriores)?DATA.duenosAnteriores.slice():[];
var ARCH=Array.isArray(DATA.archivos)?DATA.archivos.slice():[];
function E(id){return document.getElementById(id);}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function num(s){var x=parseFloat(String(s==null?'':s).replace(/[^0-9.\\-]/g,''));return isNaN(x)?0:x;}
function CLP(n){return '$'+Math.round(num(n)).toLocaleString('es-CL');}
function renderForm(){var h='';for(var s=0;s<SECS.length;s++){var sec=SECS[s];h+='<div class="sec"><h2>'+esc(sec.ico+' '+sec.t)+'</h2><div class="grid">';for(var i=0;i<sec.f.length;i++){var ff=sec.f[i];var key=ff[0];var lab=ff[1];var typ=(ff[2]==='date')?'date':'text';var v=DATA[key]==null?'':String(DATA[key]);h+='<div class="fld"><label>'+esc(lab)+'</label><input id="f_'+key+'" type="'+typ+'" value="'+esc(v)+'"></div>';}h+='</div></div>';}E('form').innerHTML=h;}
function renderAnt(){var h='<table class="rows"><tr><th>Nombre</th><th>RUT</th><th>Desde</th><th>Hasta</th><th>Arriendo</th><th>Motivo</th><th></th></tr>';for(var i=0;i<ANT.length;i++){var r=ANT[i];h+='<tr><td><input value="'+esc(r.nombre||'')+'" oninput="ANT['+i+'].nombre=this.value"></td><td><input value="'+esc(r.rut||'')+'" oninput="ANT['+i+'].rut=this.value"></td><td><input type="date" value="'+esc(r.desde||'')+'" oninput="ANT['+i+'].desde=this.value"></td><td><input type="date" value="'+esc(r.hasta||'')+'" oninput="ANT['+i+'].hasta=this.value"></td><td><input value="'+esc(r.arriendo||'')+'" oninput="ANT['+i+'].arriendo=this.value"></td><td><input value="'+esc(r.motivo||'')+'" oninput="ANT['+i+'].motivo=this.value"></td><td><button class="x" onclick="delAnt('+i+')"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6.4 6.4 17.6 17.6M17.6 6.4 6.4 17.6"/></svg></button></td></tr>';}h+='</table>';E('ant').innerHTML=h;}
function addAnt(){ANT.push({nombre:'',rut:'',desde:'',hasta:'',arriendo:'',motivo:''});renderAnt();}
function delAnt(i){ANT.splice(i,1);renderAnt();}
function renderDue(){var h='<table class="rows"><tr><th>Propietario</th><th>RUT</th><th>Desde</th><th>Hasta</th><th>Forma</th><th>Fojas/N°/Año</th><th></th></tr>';for(var i=0;i<DUE.length;i++){var r=DUE[i];h+='<tr><td><input value="'+esc(r.propietario||'')+'" oninput="DUE['+i+'].propietario=this.value"></td><td><input value="'+esc(r.rut||'')+'" oninput="DUE['+i+'].rut=this.value"></td><td><input type="date" value="'+esc(r.desde||'')+'" oninput="DUE['+i+'].desde=this.value"></td><td><input type="date" value="'+esc(r.hasta||'')+'" oninput="DUE['+i+'].hasta=this.value"></td><td><input value="'+esc(r.forma||'')+'" oninput="DUE['+i+'].forma=this.value"></td><td><input value="'+esc(r.fojas||'')+'" oninput="DUE['+i+'].fojas=this.value"></td><td><button class="x" onclick="delDue('+i+')"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6.4 6.4 17.6 17.6M17.6 6.4 6.4 17.6"/></svg></button></td></tr>';}h+='</table>';E('due').innerHTML=h;}
function addDue(){DUE.push({propietario:'',rut:'',desde:'',hasta:'',forma:'',fojas:''});renderDue();}
function delDue(i){DUE.splice(i,1);renderDue();}
function renderArch(){var h='';for(var i=0;i<ARCH.length;i++){h+='<div class="file"><a href="'+(ARCH[i].url||'#')+'" target="_blank">'+esc(ARCH[i].name||'archivo')+'</a><button class="x" onclick="delArch('+i+')"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6.4 6.4 17.6 17.6M17.6 6.4 6.4 17.6"/></svg></button></div>';}E('arch').innerHTML=h;}
function delArch(i){ARCH.splice(i,1);renderArch();}
function onFiles(inp){var files=inp.files;if(!files||!files.length)return;E('msg').style.color='#5a6678';E('msg').textContent='Subiendo archivo(s)…';var pending=files.length;Array.prototype.forEach.call(files,function(file){var rd=new FileReader();rd.onload=function(){fetch('/api/archivo/subir',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataUrl:rd.result,name:file.name})}).then(function(r){return r.json();}).then(function(j){if(j&&j.url){ARCH.push({url:j.url,name:j.name||file.name,contentType:file.type});renderArch();}pending--;if(pending<=0){E('msg').style.color='#1f9d57';E('msg').textContent='Archivo(s) adjuntado(s). Recuerda Guardar.';}}).catch(function(){pending--;E('msg').style.color='#c0392b';E('msg').textContent='No se pudo subir un archivo.';});};rd.readAsDataURL(file);});inp.value='';}
function collect(){var o={};for(var s=0;s<SECS.length;s++){for(var i=0;i<SECS[s].f.length;i++){var k=SECS[s].f[i][0];var el=E('f_'+k);o[k]=el?el.value:'';}}o.arrendatariosAnteriores=ANT;o.duenosAnteriores=DUE;o.observaciones=E('f_observaciones')?E('f_observaciones').value:'';o.archivos=ARCH;if(DATA.fichaPublicId)o.fichaPublicId=DATA.fichaPublicId;return o;}
function save(){E('msg').style.color='#5a6678';E('msg').textContent='Guardando…';fetch('/api/fc/'+FID,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ficha:collect()})}).then(function(r){return r.json();}).then(function(j){if(j&&j.ok){E('msg').style.color='#1f9d57';E('msg').textContent='✓ Guardado. Quien creó el enlace podrá traer tus cambios.';}else{E('msg').style.color='#c0392b';E('msg').textContent=(j&&j.error)||'No se pudo guardar.';}}).catch(function(){E('msg').style.color='#c0392b';E('msg').textContent='No se pudo guardar (revisa tu conexión).';});}
function buildDoc(){var f=collect();var rows='';for(var s=0;s<SECS.length;s++){var sec=SECS[s];var inner='';for(var i=0;i<sec.f.length;i++){var k=sec.f[i][0];var v=f[k];if(v&&String(v).trim())inner+='<tr><td class="l">'+esc(sec.f[i][1])+'</td><td>'+esc(v)+'</td></tr>';}if(inner)rows+='<div class="sec"><h2>'+esc(sec.ico+' '+sec.t)+'</h2><table class="kv">'+inner+'</table></div>';}var A=f.arrendatariosAnteriores.filter(function(r){return r.nombre||r.rut||r.desde||r.hasta||r.arriendo||r.motivo;});var ant='';if(A.length){ant='<div class="sec"><h2>Arrendatarios anteriores</h2><table class="grid"><tr><th>Nombre</th><th>RUT</th><th>Desde</th><th>Hasta</th><th>Arriendo</th><th>Motivo</th></tr>';A.forEach(function(r){ant+='<tr><td>'+esc(r.nombre||'')+'</td><td>'+esc(r.rut||'')+'</td><td>'+esc(r.desde||'')+'</td><td>'+esc(r.hasta||'')+'</td><td>'+esc(r.arriendo||'')+'</td><td>'+esc(r.motivo||'')+'</td></tr>';});ant+='</table></div>';}var D=f.duenosAnteriores.filter(function(r){return r.propietario||r.rut||r.desde||r.hasta||r.forma||r.fojas;});var due='';if(D.length){due='<div class="sec"><h2>Propietarios anteriores</h2><table class="grid"><tr><th>Propietario</th><th>RUT</th><th>Desde</th><th>Hasta</th><th>Forma</th><th>Fojas/N°/Año</th></tr>';D.forEach(function(r){due+='<tr><td>'+esc(r.propietario||'')+'</td><td>'+esc(r.rut||'')+'</td><td>'+esc(r.desde||'')+'</td><td>'+esc(r.hasta||'')+'</td><td>'+esc(r.forma||'')+'</td><td>'+esc(r.fojas||'')+'</td></tr>';});due+='</table></div>';}var obs=(f.observaciones&&f.observaciones.trim())?'<div class="sec"><h2>Observaciones</h2><div class="obs">'+esc(f.observaciones)+'</div></div>':'';var arch='';if(ARCH.length){arch='<div class="sec"><h2>Documentos</h2><ul>';ARCH.forEach(function(a){arch+='<li><a href="'+(a.url||'#')+'">'+esc(a.name||'archivo')+'</a></li>';});arch+='</ul></div>';}var st='<style>body{font-family:Arial,sans-serif;color:#16202f;padding:18px}h1{font-size:20px;color:#1F3A5C}.sec{margin-bottom:14px}.sec h2{color:#1F3A5C;font-size:15px;border-bottom:2px solid #1F3A5C;padding-bottom:3px;margin-bottom:6px}table{width:100%;border-collapse:collapse}table.kv td{padding:5px 7px;border-bottom:1px solid #eee;font-size:13px;vertical-align:top}table.kv td.l{width:40%;color:#5a6678;background:#f7f9fc;font-weight:bold}table.grid th{background:#1F3A5C;color:#fff;padding:5px;font-size:12px;text-align:left}table.grid td{border:1px solid #ccc;padding:4px 6px;font-size:12px}.obs{white-space:pre-wrap;font-size:13px}@media print{@page{size:A4;margin:12mm}}</style>';return '<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Ficha</title>'+st+'</head><body><h1>Ficha completa — '+esc(f.alias||'Propiedad')+'</h1>'+rows+ant+due+obs+arch+'</body></html>';}
function dl(name,content,mime){var b=new Blob([content],{type:mime});var u=URL.createObjectURL(b);var a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){URL.revokeObjectURL(u);},1500);}
function expPDF(){var w=window.open('','_blank');if(!w){dl('ficha.html',buildDoc(),'text/html');return;}w.document.open();w.document.write(buildDoc());w.document.close();setTimeout(function(){try{w.focus();w.print();}catch(e){}},600);}
function expWord(){dl('ficha_'+FID+'.doc',buildDoc(),'application/msword');}
function expExcel(){var f=collect();var rows='';for(var s=0;s<SECS.length;s++){var sec=SECS[s];var any=false;for(var i=0;i<sec.f.length;i++){if(f[sec.f[i][0]]&&String(f[sec.f[i][0]]).trim()){any=true;break;}}if(!any)continue;rows+='<tr><td colspan="2" style="background:#1F3A5C;color:#fff;font-weight:bold">'+esc(sec.t)+'</td></tr>';for(var j=0;j<sec.f.length;j++){var v=f[sec.f[j][0]];if(v&&String(v).trim())rows+='<tr><td>'+esc(sec.f[j][1])+'</td><td>'+esc(v)+'</td></tr>';}}dl('ficha_'+FID+'.xls','<html><head><meta charset="utf-8"></head><body><table border="1">'+rows+'</table></body></html>','application/vnd.ms-excel');}
function shareText(){var f=collect();var L=[];L.push('Ficha de propiedad: '+(f.alias||'Propiedad'));if(f.direccion||f.comuna)L.push(''+[f.direccion,f.comuna,f.region].filter(Boolean).join(', '));if(f.arriendoUF)L.push('Arriendo: '+f.arriendoUF+' UF');L.push('');L.push('Ficha completada en ArriendoPro.');return L.join('\\n');}
function shWA(){window.open('https://wa.me/?text='+encodeURIComponent(shareText()),'_blank');}
function shMail(){window.location.href='mailto:?subject='+encodeURIComponent('Ficha de propiedad')+'&body='+encodeURIComponent(shareText());}
function shSMS(){window.location.href='sms:?&body='+encodeURIComponent(shareText());}
E('ttl').textContent='Ficha — '+(DATA.alias||'Propiedad');
renderForm();renderAnt();renderDue();renderArch();
if(E('f_observaciones'))E('f_observaciones').value=DATA.observaciones==null?'':String(DATA.observaciones);
</script>
</body></html>`
}

export const config: Config = {
  path: '/llenar/:id',
  method: 'GET',
}
